services:
  nav:
    build: .
    container_name: nav-php
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./config.php:/var/www/html/config.php:ro
      - /srv/docker/npmplus/data:/data:ro
      - /home/falcon/GoogleDrive/Docs:/docs:ro
    ports:
      - 8085:80
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
